# Generated by Django 5.0.6 on 2024-05-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo_list.todolist'),
        ),
    ]
